#!/usr/bin/env node
/**
 * Convert LVGL icon/image C arrays to PNG files and generate TypeScript exports.
 *
 * Usage: node scripts/convert-icons.js
 *
 * Reads icon_*.c and image_*.c from ../../aura/src/
 * Writes PNG files to ./src/assets/icons/
 * Generates TypeScript exports to ./src/assets/icons.ts
 */

const fs = require('fs');
const path = require('path');

const AURA_SRC = path.resolve(__dirname, '../..', 'aura/src');
const OUTPUT_DIR = path.resolve(__dirname, '../src/assets/icons');
const TS_OUTPUT = path.resolve(__dirname, '../src/assets/icons.ts');

// List of all icon/image files to process (without .c extension)
const FILES = [
  'icon_blizzard', 'icon_blowing_snow', 'icon_clear_night', 'icon_cloudy',
  'icon_drizzle', 'icon_flurries', 'icon_haze_fog_dust_smoke', 'icon_heavy_rain',
  'icon_heavy_snow', 'icon_isolated_scattered_tstorms_day', 'icon_isolated_scattered_tstorms_night',
  'icon_mostly_clear_night', 'icon_mostly_cloudy_day', 'icon_mostly_cloudy_night',
  'icon_mostly_sunny', 'icon_partly_cloudy', 'icon_partly_cloudy_night',
  'icon_scattered_showers_day', 'icon_scattered_showers_night', 'icon_showers_rain',
  'icon_sleet_hail', 'icon_snow_showers_snow', 'icon_strong_tstorms',
  'icon_sunny', 'icon_tornado', 'icon_wintry_mix_rain_snow',
  'image_blizzard', 'image_blowing_snow', 'image_clear_night', 'image_cloudy',
  'image_drizzle', 'image_flurries', 'image_haze_fog_dust_smoke', 'image_heavy_rain',
  'image_heavy_snow', 'image_isolated_scattered_tstorms_day', 'image_isolated_scattered_tstorms_night',
  'image_mostly_clear_night', 'image_mostly_cloudy_day', 'image_mostly_cloudy_night',
  'image_mostly_sunny', 'image_partly_cloudy', 'image_partly_cloudy_night',
  'image_scattered_showers_day', 'image_scattered_showers_night', 'image_showers_rain',
  'image_sleet_hail', 'image_snow_showers_snow', 'image_strong_tstorms',
  'image_sunny', 'image_tornado', 'image_wintry_mix_rain_snow'
];

function extractBytes(content) {
  // Find the array assignment line: variable_map[] = { ... };
  const match = content.match(/(?:uint8_t|uint16_t|uint32_t)\s+\w+_map\s*=\s*\{([\s\S]*?)\};/);
  if (!match) {
    throw new Error('Could not find array definition');
  }

  const arrayBody = match[1];
  const bytes = [];

  // Parse hex bytes: 0x00, 0xA0, etc.
  const hexRegex = /0x[0-9a-fA-F]{1,2}/g;
  let hexMatch;
  while ((hexMatch = hexRegex.exec(arrayBody)) !== null) {
    bytes.push(parseInt(hexMatch[0], 16));
  }

  return Buffer.from(bytes);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function convertFile(baseName) {
  const cFile = path.join(AURA_SRC, baseName + '.c');
  const outPng = path.join(OUTPUT_DIR, baseName + '.png');

  if (!fs.existsSync(cFile)) {
    console.warn(`⚠ Missing: ${cFile}`);
    return null;
  }

  const content = fs.readFileSync(cFile, 'utf8');
  const buffer = extractBytes(content);

  // Verify PNG signature
  if (buffer.length < 8 || buffer[0] !== 0x89 || buffer[1] !== 0x50) {
    console.warn(`⚠ ${baseName}: Not a valid PNG (header: 0x${buffer[0].toString(16)}, 0x${buffer[1].toString(16)})`);
    // Still write it - it might be raw LVGL format, but proceed
  }

  fs.writeFileSync(outPng, buffer);
  console.log(`✓ ${baseName} → ${buffer.length} bytes`);

  return {
    name: baseName,
    base64: buffer.toString('base64'),
    size: buffer.length
  };
}

function generateTypeScript(exports) {
  const lines = [
    '// Auto-generated by scripts/convert-icons.js',
    '// DO NOT EDIT MANUALLY - run the conversion script instead',
    '',
    '// Weather icon images for Aura simulator',
    '// Each constant is a data URL for a PNG image',
    ''
  ];

  exports.forEach(exp => {
    lines.push(`export const ${exp.name} = "data:image/png;base64,${exp.base64}";`);
  });

  lines.push('');
  lines.push(`// Total icons: ${exports.length}`);

  return lines.join('\n');
}

function main() {
  console.log('Converting LVGL icons to PNG...\n');

  ensureDir(OUTPUT_DIR);

  const exports = [];
  let successCount = 0;
  let failCount = 0;

  for (const file of FILES) {
    try {
      const exp = convertFile(file);
      if (exp) {
        exports.push(exp);
        successCount++;
      } else {
        failCount++;
      }
    } catch (err) {
      console.error(`✗ ${file}: ${err.message}`);
      failCount++;
    }
  }

  console.log(`\nConverted ${successCount}/${FILES.length} icons successfully`);

  // Generate TypeScript file
  console.log('Generating TypeScript exports...');
  const tsContent = generateTypeScript(exports);
  fs.writeFileSync(TS_OUTPUT, tsContent);
  console.log(`✓ icons.ts written (${exports.length} exports)`);

  console.log('\nDone.');
}

main();
