/**
 * Auto-generated constants from aura/aura.ino
 * Generated: 2026-04-22T21:49:13.436Z
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated by AuraInoParser
 * To regenerate: Run the file watcher or manually invoke the parser
 */

// ============================================================================
// SCREEN DIMENSIONS
// ============================================================================

export const SCREEN = {
  width: 240 as const,
  height: 320 as const,
} as const;

// ============================================================================
// FONTS
// ============================================================================

export const FONTS = {
  size12: { size: 12, weight: 400 as const, family: 'system-ui' } as const, // aura.ino:39
  size14: { size: 14, weight: 400 as const, family: 'system-ui' } as const, // aura.ino:40
  size16: { size: 16, weight: 400 as const, family: 'system-ui' } as const, // aura.ino:41
  size20: { size: 20, weight: 400 as const, family: 'system-ui' } as const, // aura.ino:42
  size42: { size: 42, weight: 400 as const, family: 'system-ui' } as const, // aura.ino:43
} as const;

// Helper to get font by size
export function getFont(size: 12 | 14 | 16 | 20 | 42) {
  return FONTS[`size${size}`];
}

// ============================================================================
// LV_PALETTE CONSTANTS
// ============================================================================

export const LV_PALETTE = {
  RED: 0 as const,
  GREEN: 1 as const,
  BLUE: 2 as const,
  GREY: 3 as const,
} as const;

// Helper to convert LV_PALETTE constants to hex
export function lvPaletteToHex(palette: number): string {
  const paletteMap: Record<number, string> = {
    [LV_PALETTE.RED]: '#F44336',
    [LV_PALETTE.GREEN]: '#4CAF50',
    [LV_PALETTE.BLUE]: '#2196F3',
    [LV_PALETTE.GREY]: '#9E9E9E',
  };
  return paletteMap[palette] || '#9E9E9E';
}

// ============================================================================
// TIMINGS
// ============================================================================

export const TIMINGS = {
  spinnerRotation: 16 as const, // ms (aura.ino:815)
  spinnerAngleDelta: 4 as const, // degrees per tick (aura.ino:782)
  settingsTimeout: 30000 as const, // ms (aura.ino:124)
  screenOffTimeoutDefault: 30 as const, // seconds (aura.ino:75, default index)
  weatherUpdateInterval: 600000 as const, // ms (aura.ino:28)
  screenUpdateInterval: 1000 as const, // ms (aura.ino:29)
  touchWakeIgnore: 500 as const, // ms (aura.ino:422)
} as const;

// ============================================================================
// DEFAULTS
// ============================================================================

export const DEFAULTS = {
  latitude: '51.5074' as const,
  longitude: '-0.1278' as const,
  location: 'London' as const,
  dayBrightness: 128 as const,
  nightBrightness: 64 as const,
  currentLanguage: 0 as const,
  screenOffTimeoutIndex: 2 as const,
} as const;

// ============================================================================
// ALIGNMENT CONSTANTS
// ============================================================================

export const ALIGN = {
  TOP_LEFT: 'TOP_LEFT' as const,
  TOP_MID: 'TOP_MID' as const,
  TOP_RIGHT: 'TOP_RIGHT' as const,
  BOTTOM_LEFT: 'BOTTOM_LEFT' as const,
  BOTTOM_MID: 'BOTTOM_MID' as const,
  BOTTOM_RIGHT: 'BOTTOM_RIGHT' as const,
  LEFT_TOP: 'LEFT_TOP' as const,
  LEFT_MID: 'LEFT_MID' as const,
  LEFT_BOTTOM: 'LEFT_BOTTOM' as const,
  RIGHT_TOP: 'RIGHT_TOP' as const,
  RIGHT_MID: 'RIGHT_MID' as const,
  RIGHT_BOTTOM: 'RIGHT_BOTTOM' as const,
  CENTER: 'CENTER' as const,
  OUT_TOP_LEFT: 'OUT_TOP_LEFT' as const,
  OUT_TOP_MID: 'OUT_TOP_MID' as const,
  OUT_TOP_RIGHT: 'OUT_TOP_RIGHT' as const,
  OUT_BOTTOM_LEFT: 'OUT_BOTTOM_LEFT' as const,
  OUT_BOTTOM_MID: 'OUT_BOTTOM_MID' as const,
  OUT_BOTTOM_RIGHT: 'OUT_BOTTOM_RIGHT' as const,
  OUT_LEFT_TOP: 'OUT_LEFT_TOP' as const,
  OUT_LEFT_MID: 'OUT_LEFT_MID' as const,
  OUT_LEFT_BOTTOM: 'OUT_LEFT_BOTTOM' as const,
  OUT_RIGHT_TOP: 'OUT_RIGHT_TOP' as const,
  OUT_RIGHT_MID: 'OUT_RIGHT_MID' as const,
  OUT_RIGHT_BOTTOM: 'OUT_RIGHT_BOTTOM' as const,
} as const;

export type Alignment = typeof ALIGN[keyof typeof ALIGN];

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

// Extracted: 11 colors, 5 fonts, 17 positions, 16 dimensions
// Generated at: 2026-04-22T21:49:13.436Z