// Auto-generated by scripts/convert_icons.py
// DO NOT EDIT MANUALLY - run the conversion script instead

// Weather icon images for Aura simulator
// Each constant is a data URL for a PNG image


// Total icons: 0