/**
 * AuraInoParser - Extracts UI constants from aura/aura.ino
 *
 * This parser performs static analysis on the Arduino C++ file to extract:
 * - Color values (hex from lv_color_hex calls)
 * - Screen dimensions (#define SCREEN_WIDTH/HEIGHT)
 * - Font declarations (LV_FONT_DECLARE)
 * - Layout positions and sizes (from lv_obj_align, lv_obj_set_size, etc.)
 * - Default values for settings
 *
 * The parser uses regex-based extraction and does not require a full C++ parser.
 * It generates a TypeScript file with all extracted constants.
 *
 * Usage:
 *   const parser = new AuraInoParser('/path/to/aura.ino');
 *   const output = parser.parse();
 *   console.log(output);
 */

import { readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { extractColors } from './colors.ts';
import { extractScreenDimensions } from './screenDimensions.ts';
import { extractFonts } from './fonts.ts';
import { extractPositions } from './positions.ts';
import { extractDimensions } from './dimensions.ts';
import { extractDefaults } from './defaults.ts';
import type {
  ParsedColor,
  ParsedDimension,
  ParsedPosition,
  ParsedFont,
  ParsedDefaults,
  ParsedResult,
} from './types.ts';

// Get current directory for relative path resolution
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Debug flag - enables/disables debug logging
const DEBUG = import.meta.env?.DEV || import.meta.env?.VITE_DEBUG === 'true';

export type {
  ParsedColor,
  ParsedDimension,
  ParsedPosition,
  ParsedFont,
  ParsedDefaults,
  ParsedResult,
} from './types.ts';

/**
 * AuraInoParser class
 */
export class AuraInoParser {
  private auraInoPath: string;

  constructor(auraInoPath?: string) {
    // Default to ../aura/aura.ino relative to this file
    this.auraInoPath = auraInoPath || join(__dirname, '..', '..', '..', 'aura', 'aura.ino');
  }

  /**
   * Parse the aura.ino file and extract constants
   */
  async parse(): Promise<ParsedResult> {
    const content = await readFile(this.auraInoPath, 'utf-8');
    const lines = content.split('\n');

    return {
      colors: await extractColors(content, lines),
      screen: extractScreenDimensions(content, lines),
      fonts: extractFonts(content, lines),
      positions: extractPositions(content, lines),
      dimensions: extractDimensions(content, lines),
      defaults: extractDefaults(content, lines),
      timestamp: Date.now(),
    };
  }

  /**
   * Get line number from character offset
   */
  private getLineNumber(content: string, charOffset: number): number {
    const lines = content.substring(0, charOffset).split('\n');
    return lines.length;
  }

  /**
   * Generate TypeScript code from parsed result
   */
  generateTypeScript(result: ParsedResult): string {
    const lines: string[] = [];

    lines.push(`/**
 * Auto-generated constants from aura/aura.ino
 * Generated: ${new Date().toISOString()}
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated by AuraInoParser
 * To regenerate: Run the file watcher or manually invoke the parser
 */
`);

    // SCREEN first (no dependencies)
    lines.push(`// ============================================================================`);
    lines.push(`// SCREEN DIMENSIONS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const SCREEN = {`);
    lines.push(`  width: ${result.screen.width} as const,`);
    lines.push(`  height: ${result.screen.height} as const,`);
    lines.push(`} as const;`);
    lines.push(``);

    // FONTS
    lines.push(`// ============================================================================`);
    lines.push(`// FONTS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const FONTS = {`);

    for (const font of result.fonts) {
      lines.push(`  size${font.size}: { size: ${font.size}, weight: 400 as const, family: 'Montserrat' } as const, // aura.ino:${font.line}`);
    }

    lines.push(`} as const;`);
    lines.push(``);

    // COLORS
    lines.push(`// ============================================================================`);
    lines.push(`// COLORS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const COLORS = {`);

    for (const color of result.colors) {
      lines.push(`  ${color.name}: '${color.value}' as const, // aura.ino:${color.line}`);
    }

    lines.push(`} as const;`);
    lines.push(``);

    // getFont function (depends on FONTS)
    const fontSizes = result.fonts.map(f => f.size);
    lines.push(`// Helper to get font by size`);
    lines.push(`export function getFont(size: ${fontSizes.join(' | ')}) {`);
    lines.push(`  return FONTS[` + '`size${size}`' + '];');
    lines.push(`}`);
    lines.push(``);

    // LV_PALETTE (needed by COLORS)
    lines.push(`// ============================================================================`);
    lines.push(`// LV_PALETTE CONSTANTS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const LV_PALETTE = {`);
    lines.push(`  RED: 0 as const,`);
    lines.push(`  GREEN: 1 as const,`);
    lines.push(`  BLUE: 2 as const,`);
    lines.push(`  GREY: 3 as const,`);
    lines.push(`} as const;`);
    lines.push(``);

    lines.push(`// Helper to convert LV_PALETTE constants to hex`);
    lines.push(`export function lvPaletteToHex(palette: number): string {`);
    lines.push(`  const paletteMap: Record<number, string> = {`);
    lines.push(`    [LV_PALETTE.RED]: '#F44336',`);
    lines.push(`    [LV_PALETTE.GREEN]: '#4CAF50',`);
    lines.push(`    [LV_PALETTE.BLUE]: '#2196F3',`);
    lines.push(`    [LV_PALETTE.GREY]: '#9E9E9E',`);
    lines.push(`  };`);
    lines.push(`  return paletteMap[palette] || '#9E9E9E';`);
    lines.push(`}`);
    lines.push(``);

    // COLORS are defined manually in Constants.ts to allow custom naming
    // (some hex values have multiple semantic names)
    // TIMINGS
    lines.push(`// ============================================================================`);
    lines.push(`// TIMINGS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const TIMINGS = {`);
    lines.push(`  spinnerRotation: 16 as const, // ms (aura.ino:815)`);
    lines.push(`  spinnerAngleDelta: 4 as const, // degrees per tick (aura.ino:782)`);
    lines.push(`  settingsTimeout: 30000 as const, // ms (aura.ino:124)`);
    lines.push(`  screenOffTimeoutDefault: 30 as const, // seconds (aura.ino:75, default index)`);
    lines.push(`  weatherUpdateInterval: 600000 as const, // ms (aura.ino:28)`);
    lines.push(`  screenUpdateInterval: 1000 as const, // ms (aura.ino:29)`);
    lines.push(`  touchWakeIgnore: 500 as const, // ms (aura.ino:422)`);
    lines.push(`} as const;`);
    lines.push(``);

    // DEFAULTS
    lines.push(`// ============================================================================`);
    lines.push(`// DEFAULTS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const DEFAULTS = {`);
    lines.push(`  latitude: '${result.defaults.latitude}' as const,`);
    lines.push(`  longitude: '${result.defaults.longitude}' as const,`);
    lines.push(`  location: '${result.defaults.location}' as const,`);
    lines.push(`  dayBrightness: ${result.defaults.dayBrightness} as const,`);
    lines.push(`  nightBrightness: ${result.defaults.nightBrightness} as const,`);
    lines.push(`  currentLanguage: ${result.defaults.currentLanguage} as const,`);
    lines.push(`  screenOffTimeoutIndex: ${result.defaults.screenOffTimeoutIndex} as const,`);
    lines.push(`} as const;`);
    lines.push(``);

    // ALIGN
    lines.push(`// ============================================================================`);
    lines.push(`// ALIGNMENT CONSTANTS`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`export const ALIGN = {`);
    lines.push(`  TOP_LEFT: 'TOP_LEFT' as const,`);
    lines.push(`  TOP_MID: 'TOP_MID' as const,`);
    lines.push(`  TOP_RIGHT: 'TOP_RIGHT' as const,`);
    lines.push(`  BOTTOM_LEFT: 'BOTTOM_LEFT' as const,`);
    lines.push(`  BOTTOM_MID: 'BOTTOM_MID' as const,`);
    lines.push(`  BOTTOM_RIGHT: 'BOTTOM_RIGHT' as const,`);
    lines.push(`  LEFT_TOP: 'LEFT_TOP' as const,`);
    lines.push(`  LEFT_MID: 'LEFT_MID' as const,`);
    lines.push(`  LEFT_BOTTOM: 'LEFT_BOTTOM' as const,`);
    lines.push(`  RIGHT_TOP: 'RIGHT_TOP' as const,`);
    lines.push(`  RIGHT_MID: 'RIGHT_MID' as const,`);
    lines.push(`  RIGHT_BOTTOM: 'RIGHT_BOTTOM' as const,`);
    lines.push(`  CENTER: 'CENTER' as const,`);
    lines.push(`  OUT_TOP_LEFT: 'OUT_TOP_LEFT' as const,`);
    lines.push(`  OUT_TOP_MID: 'OUT_TOP_MID' as const,`);
    lines.push(`  OUT_TOP_RIGHT: 'OUT_TOP_RIGHT' as const,`);
    lines.push(`  OUT_BOTTOM_LEFT: 'OUT_BOTTOM_LEFT' as const,`);
    lines.push(`  OUT_BOTTOM_MID: 'OUT_BOTTOM_MID' as const,`);
    lines.push(`  OUT_BOTTOM_RIGHT: 'OUT_BOTTOM_RIGHT' as const,`);
    lines.push(`  OUT_LEFT_TOP: 'OUT_LEFT_TOP' as const,`);
    lines.push(`  OUT_LEFT_MID: 'OUT_LEFT_MID' as const,`);
    lines.push(`  OUT_LEFT_BOTTOM: 'OUT_LEFT_BOTTOM' as const,`);
    lines.push(`  OUT_RIGHT_TOP: 'OUT_RIGHT_TOP' as const,`);
    lines.push(`  OUT_RIGHT_MID: 'OUT_RIGHT_MID' as const,`);
    lines.push(`  OUT_RIGHT_BOTTOM: 'OUT_RIGHT_BOTTOM' as const,`);
    lines.push(`} as const;`);
    lines.push(``);
    lines.push(`export type Alignment = typeof ALIGN[keyof typeof ALIGN];`);
    lines.push(``);

    lines.push(`// ============================================================================`);
    lines.push(`// EXPORT SUMMARY`);
    lines.push(`// ============================================================================`);
    lines.push(``);
    lines.push(`// Extracted: ${result.colors.length} colors, ${result.fonts.length} fonts, ${result.positions.length} positions, ${result.dimensions.length} dimensions`);
    lines.push(`// Generated at: ${new Date().toISOString()}`);

    return lines.join('\n');
  }

  /**
   * Parse and generate the TypeScript file
   */
  async generateFile(outputPath?: string): Promise<string> {
    const result = await this.parse();
    const typescript = this.generateTypeScript(result);

    if (outputPath) {
      const fs = await import('fs');
      await fs.promises.writeFile(outputPath, typescript, 'utf-8');
      if (DEBUG) {
        console.debug('[AuraInoParser] Generated constants at:', outputPath);
      }
    }

    return typescript;
  }
}

// Standalone function for CLI usage
export async function parseAuraIno(inputPath?: string, outputPath?: string): Promise<string> {
  const parser = new AuraInoParser(inputPath);
  return await parser.generateFile(outputPath);
}

// Allow running as standalone script
if (import.meta.url === `file://${process.argv[1]}`) {
  const inputPath = process.argv[2] && process.argv[2] !== 'undefined' ? process.argv[2] : undefined;
  const outputPath = process.argv[3];
  parseAuraIno(inputPath, outputPath)
    .catch(err => console.error('Parse failed:', err));
}
